name: hive_todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_spinkit: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Sahel
      fonts:
        - asset: assets/fonts/sahel.ttf

    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir.ttf

    - family: Mh
      fonts:
        - asset: assets/fonts/mh.ttf
